apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: my-kafka-source3
spec:
  image: quay.io/redhatdemo/kafka-src
  args: 
    - '--bootstrap=9.59.193.46:9092'
    - '--topic=test'
    - '--groupId=foobar'
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: message-dumper
