apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: my-kafka-source8
spec:
  image: quay.io/matzew/kafka-src
  args: 
    - '--bootstrap=9.59.193.46:9092'
    - '--topic=test'
    - '--groupId=foobar8'
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: message-dumper8
